### ISSUE TITLE
netdna.bootstrapcdn.com

### ISSUE THREAD

**Issue by tasi788** [logroid/adaway-hosts#3]
### Description:
* **Current behaviour**: 
block `netdna.bootstrapcdn.com` incorrectly
* **Expected behaviour**: 
should passed away.

### Additional Information
according to [wiki](https://en.wikipedia.org/wiki/BootstrapCDN) `bootstrap` used to serve file with NetDNA, and there's many developer still using it (which will redirect to `stackpath.bootstrapcdn.com` as well), so it doesn't make sense to block  `netdna.bootstrapcdn.com`.

**Comment by logroid** [comment]
fixed 213c252
thank you😄
