### ISSUE TITLE
Remove: ipe-pmt.prod.sabre.com

### ISSUE THREAD

**Issue by YipYup** [logroid/adaway-hosts#4]
Hello. The hostname `ipe-pmt.prod.sabre.com` is currently blocked by this list. The domain is used for authorizing payment when purchasing airline tickets at the website at `jetblue.com`. I am requesting removal of `ipe-pmt.prod.sabre.com` from the list.

**Comment by logroid** [comment]
Thank you.  
ipe-pmt.prod.sabre.com is not on the list.  
sabre.com is it?

**Comment by logroid** [comment]
NextDNS and AdAway differ in the way they match hostnames.
NextDNS allows subdomains, while AdAway matches by FQDN.
The target domain will be removed, but please understand that these hosts are only maintained for AdAway.

**Comment by logroid** [comment]
fix ed211367892e0dcbe865d2f05d5d05edfa488b7c
